### ISSUE TITLE
to use tenor as default gif 

### ISSUE THREAD

**Issue by psynite69** [Zandercraft/Zandercraft-Bot#214]
+gif feature of zandercraft bot uses giphy as its default gif but that is not always accurate.
but the gif give by tenor is mostly accurate 
therefore,i would like have a request to include tenor.

**Comment by ZandercraftGames** [comment]
Thanks for your suggestion! We've considered it for implementation in our new codebase and still will, but we've found that Tenor's ratelimits are too restrictive for our use with the bot. People can easily max them out in a few minutes of sitting requesting GIFs. We may, however, work on improving the method by which we search Giphy.
