### ISSUE TITLE
Music Bugs When Forcefully Disconnected

### ISSUE THREAD

**Issue by Kashalls** [Zandercraft/Zandercraft-Bot#220]
Forcefully disconnecting the bot while the bot is playing will cause its states to be mismatched.

We should be listening to the channel disconnect event to determine if we left the channel to destroy the music player.

**Comment by ZandercraftGames** [comment]
This issue will be resolved in the discord.py rewrite.

**Comment by ZandercraftGames** [comment]
Fixed in new codebase.
